[book]
authors = ["Rollup Boost Core Contributors"]
language = "en"
src = "src"
title = "Rollup Boost"
description = "The Rollup Boost is a sidecar to enable rollup extensions"

[output.html]
theme = "theme"
git-repository-url = "https://github.com/flashbots/rollup-boost"
default-theme = "ayu"
no-section-label = true

[output.html.fold]
enable = true
level = 1

[preprocessor.mermaid]
command = "mdbook-mermaid"

[build]
build-dir = "book"
