name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install op-reth
        uses: flashbots/flashbots-toolchain@v0.2
        with:
          op-reth: latest

      - name: Download op-reth
        run: |
          ./scripts/download-op-reth.sh
          echo "$(pwd)" >> $GITHUB_PATH

      - name: Log Op-reth version
        run: |
          op-reth --version

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test --features integration -- integration::integration_test::tests

      - name: Create tar archive of integration logs
        if: ${{ failure() }}
        run: |
          # Find and archive only the logs directories. There were some issues archiving the entire directory.
          find integration_logs -type d -name "logs" | tar -czvf integration_logs.tar.gz -T -

      - name: Archive integration logs
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: integration-logs
          path: integration_logs.tar.gz
          retention-days: 5
          if-no-files-found: error
